### ISSUE TITLE
Error and warning for the simulation example 

### ISSUE THREAD

**Issue by fadeh2013** [oezgesahin/vineclust#1]
Hi,

I hope you are doing well. I attempted to replicate both real-world and simulated examples. I had an issue with the simulation and wanted to report it, but I fixed it myself. Sorry for bothering you. 

Regards,

**Comment by oezgesahin** [comment]
Hi, apologies for the late reaction. It's good to hear that the issue was resolved. If you encounter any others, let me know freely.
